# conda env create --file environment.yml
name: objectdetection
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.7.9
  - pip:
    - pyhere
    - virtualenv
    # create virtual environment using virtualenv
post-link: |
    virtualenv venv
    source venv/Scripts/activate
    pip install -r requirements.txt